name: Deploy Flutter to GitHub Pages

on:
  push:
    branches: [ main ]
  workflow_dispatch: {}

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable
          flutter-version: 3.8.1
          cache: true

      - name: Install deps
        run: flutter pub get

      - name: Build web
        run: flutter build web --release

      - name: Upload artifact for GitHub Pages
        uses: actions/upload-pages-artifact@v1
        with:
          path: build/web

      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v1
